file_length:
  warning: 800
  error: 1500
function_body_length:
 warning: 50
 error: 60
line_length:
 - 300 # warning
 - 600 # error
identifier_name:
  min_length: 2
disabled_rules:
 - force_cast
 - function_parameter_count
cyclomatic_complexity: 20
nesting:
  type_level: 2
