# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Free Bank' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Free Bank
  
  pod 'AMPopTip','4.4.0'
  
  pod 'LayoutHelper', '1.0.0'

  pod 'MBProgressHUD', '1.2.0'
  
  pod 'PKHUD','5.3.0'
  
  pod 'ReachabilitySwift', '5.0.0'
  
  pod 'SwiftyGif', '5.4.0'
  
  pod 'SkyFloatingLabelTextField','4.0.0'
  
  pod 'SwiftLint', '0.43.1'
  
end
