# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Free Bank' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Free Bank
  pod 'SwiftLint', '0.43.1'

end
